config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :pins
	
#	get 'pins/index'
  
	root 'pins#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])

  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote] 
  before_action :authenticate_user!, except: [:index, :show]

  def index
  	@pins = Pin.all.order("created_at DESC")
  end


  def show

  end

  def new
  	@pin = current_user.pins.build
  end


  def create
  	@pin = current_user.pins.build(pin_params)

  	if 	@pin.save
  		redirect_to @pin 
  	else
  		render "new"
  	end
  end

  def edit

  end
	
  def update
  	if @pin.update(pin_params)
  		redirect_to @pin
  	else
  		render "edit"
  	end
  end
	
	  def destroy
    @pin.destroy
    redirect_to root_path
  end

	private
	
	def pin_params 
		params.require(:pin).permit(:title, :description)			
	end
	
	def find_pin
		@pin = Pin.find(params[:id])
	end
end
	

	
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<form class="nav-form navbar-default">
			<div class="container">
				<%= link_to "Pinterest", root_path, class:"navbar-brand" %>
					<div class="navbar-form navbar-right">
   
						<% if user_signed_in? %>
						<%= link_to "Create new pin", new_pin_path, class:"btn btn-primary"%>
						<%= link_to "Account Settings", edit_user_registration_path, class:"btn btn-primary" %>
						<%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary" %>
						<% else %>
						<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary"%>
						<%= link_to "Sign In", new_user_session_path, class:"btn btn-primary" %>
						<% end %>
				</div>
			</div>
						
				</form>
				<div class="container">
				<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
				<%= yield %>
				</div>
  </body>
</html>

app/views/pins/_form.html.erb
<div class="form-group form-signin">
<%= simple_form_for @pin, html: { multipart: true } do|f| %>

  	<%= f.input :title %>
  	<%= f.input :description %>
  	<%= f.button :submit, class:"btn btn-primary" %>
<% end %>

</div>

app/views/pins/edit.html.erb
<div class="container">

	<h1>Edit Pin</h1>

		<%= render "form" %>

</div>

app/views/pins/index.html.erb
<p><% @pins.each do |pin| %></p>
<p class="title"><%= link_to pin.title, pin %>
<br>
<% end %>

app/views/pins/new.html.erb
<div class="container">

	<h1>New Pin</h1>


		<%= render "form", pin: @pin %>

	</div>

app/views/pins/show.html.erb
	<h1><%= @pin.title %></h1>
	<br>

	<p class="description"><%= @pin.description %></p>

		<br>

  

			<%= link_to "Back", root_path, class:"btn btn-default btn-sm" %>

	<% if user_signed_in? %>
			<%= link_to "Edit", edit_pin_path, class:"btn btn-default btn-sm"  %>

			<%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"},
			class:"btn btn-default btn-sm"  %>

	<% end %>